
[[redirects]]
  from = "/object/:object"
  to = "/object/[tokenId].html?object=:tokenId"
  status = 200

[[redirects]]
  from = "/collection/:collection"
  to = "/collection/[account].html?object=:account"
  status = 200

[[redirects]]
  from = "/mint/:mint"
  to = "/mint/:mint"
  status = 200

[[redirects]]
  from = "/gallery/:gallery"
  to = "/gallery/:gallery"
  status = 200