
[[redirects]]
  from = "/object/:object"
  to = "/object/[object].html?object=:object"
  status = 200

[[redirects]]
  from = "/collection/:collection"
  to = "/collection/[collection].html?collection=:collection"
  status = 200

[[redirects]]
  from = "/mint/:mint"
  to = "/mint/:mint"
  status = 200

[[redirects]]
  from = "/explore/:explore"
  to = "/explore/:explore"
  status = 200